# Generated by Django 3.1.6 on 2021-03-30 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pc_calculator', '0002_semester_period_order_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programoutcomeresult',
            options={'ordering': ['course']},
        ),
        migrations.RemoveConstraint(
            model_name='semester',
            name='unique_active',
        ),
    ]
