# Generated by Django 3.1.6 on 2021-09-16 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc_calculator', '0004_course_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='active',
        ),
        migrations.AddField(
            model_name='semester',
            name='offered_courses',
            field=models.ManyToManyField(to='pc_calculator.Course'),
        ),
    ]
