# Generated by Django 3.2 on 2022-06-12 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pc_calculator', '0005_auto_20210916_1300'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('member_courses', models.ManyToManyField(to='pc_calculator.Course')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='assigned_curriculum',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pc_calculator.curriculum'),
        ),
    ]
