# Generated by Django 3.2 on 2022-06-11 16:03

from django.db import migrations


def create_default_curriculum(apps, schema_editor):
    Curriculum = apps.get_model('pc_calculator', 'Curriculum')
    Curriculum.objects.create(name='Default Curriculum')


def revert_create_default_curriculum(apps, schema_editor):
    Curriculum = apps.get_model('pc_calculator', 'Curriculum')
    default_curriculum = Curriculum.objects.get(name='Default Curriculum')
    default_curriculum.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('pc_calculator', '0006_auto_20220611_1858'),
    ]

    operations = [
        migrations.RunPython(create_default_curriculum, revert_create_default_curriculum)
    ]
