# Generated by Django 3.0.3 on 2020-03-01 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=9)),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='CourseOutcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('code', models.CharField(max_length=5)),
                ('courses', models.ManyToManyField(to='courseoutcome.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_interval', models.CharField(max_length=9)),
                ('period_name', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=11)),
                ('name', models.CharField(max_length=60)),
                ('vertical_transfer', models.BooleanField(default=False)),
                ('double_major_student', models.BooleanField(default=False)),
                ('graduated_on', models.DateField(blank=True, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseoutcome.Department')),
            ],
        ),
        migrations.CreateModel(
            name='CourseOutcomeResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satisfaction', models.CharField(max_length=1)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseoutcome.Course')),
                ('course_outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseoutcome.CourseOutcome')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseoutcome.Semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseoutcome.Student')),
            ],
        ),
        migrations.CreateModel(
            name='CourseOutcomeAverage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_satisfaction', models.IntegerField()),
                ('course_outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseoutcome.CourseOutcome')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseoutcome.Semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseoutcome.Student')),
            ],
        ),
    ]
